[package]
name = "wave-generator"
version = "0.1.0"
authors = ["Yuki Kishino"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.32"
